//! Where results go (BENCHMARKS §1): the `benchmarks` table, `bench-results/<date>-<machine>.json`
//! and a Markdown summary in `docs/benchmarks/<date>-<machine>.md`. A day's file holds the latest
//! run of each suite on that machine, so re-running a suite replaces its section.

use crate::machine::Machine;
use crate::stats::Metric;
use serde::{Deserialize, Serialize};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

/// One suite's run.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SuiteResult {
    pub suite: String,
    /// Unix milliseconds.
    pub started_at: i64,
    pub runs: u32,
    pub warmup: u32,
    pub metrics: Vec<Metric>,
    /// What was measured and how, and anything a reader needs to interpret the numbers.
    pub notes: Vec<String>,
}

/// A day's results on one machine.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DayResults {
    pub date: String,
    pub machine: Machine,
    pub suites: Vec<SuiteResult>,
}

pub fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| i64::try_from(d.as_millis()).unwrap_or(i64::MAX))
}

/// "YYYY-MM-DD" (UTC) for Unix milliseconds.
pub fn date(ms: i64) -> String {
    // Howard Hinnant's days-to-civil algorithm.
    let days = ms.div_euclid(86_400_000);
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = yoe + era * 400 + i64::from(m <= 2);
    format!("{y:04}-{m:02}-{d:02}")
}

pub struct Output {
    pub root: PathBuf,
}

impl Output {
    fn json_path(&self, date: &str, machine: &Machine) -> PathBuf {
        self.root
            .join("bench-results")
            .join(format!("{date}-{}.json", machine.id))
    }

    fn markdown_path(&self, date: &str, machine: &Machine) -> PathBuf {
        self.root
            .join("docs")
            .join("benchmarks")
            .join(format!("{date}-{}.md", machine.id))
    }

    /// Merges `result` into the day's file and rewrites its Markdown summary. Returns both paths.
    pub fn save(
        &self,
        machine: &Machine,
        result: &SuiteResult,
    ) -> Result<(PathBuf, PathBuf), String> {
        let day = date(result.started_at);
        let json = self.json_path(&day, machine);
        let mut results = std::fs::read_to_string(&json)
            .ok()
            .and_then(|s| serde_json::from_str::<DayResults>(&s).ok())
            .filter(|r| r.machine.id == machine.id)
            .unwrap_or_else(|| DayResults {
                date: day.clone(),
                machine: machine.clone(),
                suites: Vec::new(),
            });
        results.machine = machine.clone();
        results.suites.retain(|s| s.suite != result.suite);
        results.suites.push(result.clone());
        results.suites.sort_by(|a, b| a.suite.cmp(&b.suite));

        write(
            &json,
            &serde_json::to_string_pretty(&results).map_err(|e| e.to_string())?,
        )?;
        let md = self.markdown_path(&day, machine);
        write(&md, &markdown(&results))?;
        Ok((json, md))
    }
}

fn write(path: &Path, text: &str) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    std::fs::write(path, format!("{text}\n")).map_err(|e| format!("{}: {e}", path.display()))
}

fn number(v: f64) -> String {
    if v.abs() >= 100.0 {
        format!("{v:.0}")
    } else if v.abs() >= 10.0 {
        format!("{v:.1}")
    } else {
        format!("{v:.2}")
    }
}

pub fn markdown(results: &DayResults) -> String {
    let mut md = String::new();
    let _ = writeln!(
        md,
        "# Benchmarks · {} · {}",
        results.date, results.machine.id
    );
    let _ = writeln!(md);
    let _ = writeln!(md, "Machine: {}", results.machine.describe());
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Generated by `kivo-bench` ([BENCHMARKS.md](../architecture/BENCHMARKS.md)); raw samples \
         in `bench-results/{}-{}.json`.",
        results.date, results.machine.id
    );
    for suite in &results.suites {
        let _ = writeln!(md);
        let _ = writeln!(md, "## `{}`", suite.suite);
        let _ = writeln!(md);
        let _ = writeln!(
            md,
            "{} runs after {} warmup (warmup excluded).",
            suite.runs, suite.warmup
        );
        let _ = writeln!(md);
        let _ = writeln!(md, "| Metric | p50 | p95 | min | max | unit |");
        let _ = writeln!(md, "|---|---|---|---|---|---|");
        for m in &suite.metrics {
            let _ = writeln!(
                md,
                "| {} | {} | {} | {} | {} | {} |",
                m.name,
                number(m.p50),
                number(m.p95),
                number(m.min),
                number(m.max),
                m.unit
            );
        }
        if !suite.notes.is_empty() {
            let _ = writeln!(md);
            for note in &suite.notes {
                let _ = writeln!(md, "- {note}");
            }
        }
    }
    md.trim_end().to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn machine(id: &str) -> Machine {
        Machine {
            id: id.into(),
            cpu: "CPU".into(),
            logical_cpus: 8,
            ram_mb: 16_384,
            gpus: Vec::new(),
            os: "Windows 11".into(),
            power: "AC".into(),
        }
    }

    fn result(suite: &str, p: f64) -> SuiteResult {
        SuiteResult {
            suite: suite.into(),
            started_at: 1_790_000_000_000,
            runs: 5,
            warmup: 1,
            metrics: vec![Metric::new("latency", "ms", true, vec![p; 5])],
            notes: vec!["a note".into()],
        }
    }

    #[test]
    fn unix_days_become_calendar_dates() {
        assert_eq!(date(0), "1970-01-01");
        assert_eq!(date(951_782_400_000), "2000-02-29");
        assert_eq!(date(1_790_000_000_000), "2026-09-21");
        assert_eq!(date(-86_400_000), "1969-12-31");
    }

    #[test]
    fn a_rerun_replaces_its_suite_and_keeps_the_others() {
        let dir = tempfile::tempdir().unwrap();
        let out = Output {
            root: dir.path().into(),
        };
        let m = machine("pc");
        out.save(&m, &result("ipc", 1.0)).unwrap();
        out.save(&m, &result("idle", 2.0)).unwrap();
        let (json, md) = out.save(&m, &result("ipc", 3.0)).unwrap();

        let day: DayResults =
            serde_json::from_str(&std::fs::read_to_string(json).unwrap()).unwrap();
        let suites: Vec<_> = day
            .suites
            .iter()
            .map(|s| (s.suite.as_str(), s.metrics[0].p50))
            .collect();
        assert_eq!(suites, [("idle", 2.0), ("ipc", 3.0)]);
        let md = std::fs::read_to_string(md).unwrap();
        assert!(md.contains("## `idle`") && md.contains("## `ipc`"));
        assert!(md.contains("| latency | 3.00 | 3.00 | 3.00 | 3.00 | ms |"));
        assert!(md.contains("- a note"));
    }
}
