[package]
name = "kivo-platform-windows"
description = "Windows implementations of the kivo-platform traits."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kivo-platform.workspace = true
windows = { workspace = true, features = ["Wdk_System_SystemServices", "Win32_System_SystemInformation", "Win32_System_Registry", "Win32_Storage_Packaging_Appx", "Win32_Graphics_DXCore", "Win32_Foundation"] }

[lints]
workspace = true
