#!/usr/bin/env node
// Mirrors every "## Build checklist" item from the specs into docs/ROADMAP.md, grouped by
// milestone and spec, and regenerates the progress table. Run after marking items: `pnpm docs:sync`.
//
// The specs are the source of truth for item status. If an item's box was changed in the
// ROADMAP copy but not in its spec, the script stops without writing, so no mark is lost.
// Also checks: duplicate IDs, unknown milestone tags, [x]/[~]/[-] items missing their "→" note.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const docs = join(root, "docs");
const sources = [
  ...readdirSync(join(docs, "architecture")).filter((f) => f.endsWith(".md")).sort().map((f) => join(docs, "architecture", f)),
  join(docs, "design", "DESIGN_SYSTEM.md"),
  join(docs, "KIVO_Project_Plan.md"),
];

const MILESTONES = ["D0", "M0", "M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "L1", "L2", "L3", "L4", "L5", "Post"];
const SPEC_LINE = /^- \[(.)\] \*\*([A-Z]+-\d+)\*\* · ([A-Za-z0-9]+) · (.*)$/;
const COPY_LINE = /^- \[(.)\] \*\*([A-Z]+-\d+)\*\* · /;
const EXIT_LINE = /^- \[(.)\] \*\*([A-Za-z0-9]+)-X\d+\*\*/;

const items = [];
const errors = [];

for (const file of sources) {
  readFileSync(file, "utf8").split(/\r?\n/).forEach((line, i) => {
    const m = SPEC_LINE.exec(line);
    if (!m) return;
    const [, mark, id, ms, text] = m;
    const where = `${relative(root, file)}:${i + 1}`;
    if (!" x~-".includes(mark)) errors.push(`${where} ${id}: unknown mark [${mark}]`);
    if (!MILESTONES.includes(ms)) errors.push(`${where} ${id}: unknown milestone "${ms}"`);
    if (mark !== " " && !text.includes("→")) errors.push(`${where} ${id}: [${mark}] needs a "→ …" note (docs/README.md §3)`);
    items.push({ id, mark, ms, text, file: relative(docs, file).replaceAll("\\", "/") });
  });
}
const byId = new Map();
for (const it of items) {
  if (byId.has(it.id)) errors.push(`duplicate ID ${it.id} in ${it.file} and ${byId.get(it.id).file}`);
  byId.set(it.id, it);
}

const roadmapPath = join(docs, "ROADMAP.md");
let roadmap = readFileSync(roadmapPath, "utf8");

// Refuse to overwrite marks that were changed only in the ROADMAP copy.
for (const line of roadmap.split(/\r?\n/)) {
  const m = COPY_LINE.exec(line);
  if (!m) continue;
  const it = byId.get(m[2]);
  if (it && it.mark !== m[1]) {
    errors.push(`${m[2]} is [${m[1]}] in ROADMAP.md but [${it.mark}] in ${it.file}: mark it in the spec (with its "→" note), then re-run`);
  }
}

const count = (group) => {
  const n = (k) => group.filter((it) => it.mark === k).length;
  return { total: group.length, done: n("x"), partial: n("~"), dropped: n("-"), todo: n(" ") };
};

const exits = {};
for (const line of roadmap.split(/\r?\n/)) {
  const m = EXIT_LINE.exec(line);
  if (!m) continue;
  (exits[m[2]] ??= { total: 0, done: 0 }).total++;
  if (m[1] === "x") exits[m[2]].done++;
}

const itemBlock = (ms) => {
  const group = items.filter((it) => it.ms === ms);
  if (!group.length) return "_No items._";
  const c = count(group);
  const out = [
    `**${c.total} items** · ✅ ${c.done} done · 🟡 ${c.partial} partial · ⏭ ${c.dropped} dropped · ⬜ ${c.todo} not started`,
    "",
    "> Generated by `pnpm docs:sync` from the specs. Mark items **in their spec** (with the `→` note), then re-run.",
  ];
  for (const file of [...new Set(group.map((it) => it.file))]) {
    const inFile = group.filter((it) => it.file === file);
    const name = file.split("/").pop();
    out.push("", `#### [${name}](${file}) (${inFile.length})`, "");
    for (const it of inFile) out.push(`- [${it.mark}] **${it.id}** · ${it.text}`);
  }
  return out.join("\n");
};

const progress = () => {
  const rows = MILESTONES.filter((ms) => items.some((it) => it.ms === ms)).map((ms) => {
    const c = count(items.filter((it) => it.ms === ms));
    const pct = Math.round((100 * (c.done + c.dropped)) / c.total);
    const ex = exits[ms] ? `${exits[ms].done}/${exits[ms].total}` : "—";
    const state = c.done + c.dropped === c.total && (!exits[ms] || exits[ms].done === exits[ms].total)
      ? "✅ Complete" : c.done + c.partial > 0 ? "🟡 In progress" : "⬜ Not started";
    return `| [${ms}](#${ms.toLowerCase()}) | ${state} | ${c.total} | ${c.done} | ${c.partial} | ${c.dropped} | ${c.todo} | ${pct}% | ${ex} |`;
  });
  const c = count(items);
  return [
    "| Milestone | State | Items | ✅ Done | 🟡 Partial | ⏭ Dropped | ⬜ Not started | Complete | Exit criteria |",
    "|---|---|---|---|---|---|---|---|---|",
    ...rows,
    `| **Total** | | **${c.total}** | **${c.done}** | **${c.partial}** | **${c.dropped}** | **${c.todo}** | **${Math.round((100 * (c.done + c.dropped)) / c.total)}%** | |`,
  ].join("\n");
};

// Every item must be named in its own milestone's build order, and a build order may only
// name items of that milestone, so the ordered plan and the tags can never drift apart.
for (const ms of MILESTONES) {
  const planned = /^(D0|M\d)$/.test(ms);
  const start = roadmap.indexOf(`<a id="${ms.toLowerCase()}"></a>`);
  const end = roadmap.indexOf(`### ${ms} items`);
  if (start < 0 || end < start) {
    if (planned) errors.push(`ROADMAP.md has no "${ms}" section (anchor + "### ${ms} items")`);
    continue;
  }
  const section = roadmap.slice(start, end);
  if (!section.includes("**Build order:**")) {
    if (planned) errors.push(`ROADMAP.md's ${ms} section has no "**Build order:**"`);
    continue;
  }
  const order = section.split("**Build order:**")[1];
  const named = new Set(order.match(/\b[A-Z]+-\d+\b/g) ?? []);
  for (const it of items.filter((i) => i.ms === ms)) {
    if (!named.has(it.id)) errors.push(`${it.id} (${ms}) is not named in the ${ms} build order in ROADMAP.md`);
  }
  for (const id of named) {
    const it = byId.get(id);
    if (!it) errors.push(`${ms} build order names unknown item ${id}`);
    else if (it.ms !== ms) errors.push(`${ms} build order names ${id}, which is tagged ${it.ms}`);
  }
}

if (errors.length) {
  console.error("docs:sync found problems (ROADMAP.md not written):\n" + errors.map((e) => `  ✗ ${e}`).join("\n"));
  process.exit(1);
}

roadmap = roadmap.replace(/<!-- progress -->[\s\S]*?<!-- \/progress -->/, `<!-- progress -->\n${progress()}\n<!-- /progress -->`);
roadmap = roadmap.replace(/<!-- items:([A-Za-z0-9]+) -->[\s\S]*?<!-- \/items -->/g, (_, ms) => `<!-- items:${ms} -->\n${itemBlock(ms)}\n<!-- /items -->`);
writeFileSync(roadmapPath, roadmap);
console.log(`${items.length} items synced into docs/ROADMAP.md`);
